package com.tradingapp.metatrader.app.features.backtest.export.html

import com.tradingapp.metatrader.domain.models.backtest.BacktestResult
import java.util.Locale
import kotlin.math.roundToInt

object BacktestHtmlReportBuilder {

    fun build(result: BacktestResult): String {
        val m = result.metrics
        val cfg = result.config

        val net = fmt(m.netProfit)
        val gp = fmt(m.grossProfit)
        val gl = fmt(m.grossLoss)
        val dd = fmt(m.maxDrawdown)
        val pf = if (m.profitFactor.isInfinite()) "∞" else String.format(Locale.US, "%.2f", m.profitFactor)
        val wr = String.format(Locale.US, "%.1f%%", m.winRate * 100.0)
        val ep = fmt(m.expectedPayoff)
        val rf = if (m.recoveryFactor.isInfinite()) "∞" else String.format(Locale.US, "%.2f", m.recoveryFactor)
        val sharpe = String.format(Locale.US, "%.3f", m.sharpeLike)

        val sl = if (cfg.stopLossPoints > 0) "${cfg.stopLossPoints} pts" else "Disabled"
        val tp = if (cfg.takeProfitPoints > 0) "${cfg.takeProfitPoints} pts" else "Disabled"
        val risk = if (cfg.riskPercent > 0) "${cfg.riskPercent}%" else "Manual lots"

        val tradesRows = buildTradesTable(result)

        return """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Backtest Report</title>
<style>
  body { font-family: Arial, sans-serif; background:#0b1220; color:#d1d4dc; margin:0; padding:18px; }
  .card { background:#121a2b; padding:16px; border-radius:12px; margin-bottom:14px; }
  h1 { font-size:20px; margin:0 0 10px 0; }
  h2 { font-size:16px; margin:0 0 10px 0; color:#8aa0c6; }
  table { width:100%; border-collapse:collapse; }
  th, td { padding:10px; border-bottom:1px solid #1f2a44; font-size:13px; }
  th { text-align:left; color:#8aa0c6; }
  .pos { color:#4caf50; font-weight:bold; }
  .neg { color:#ef5350; font-weight:bold; }
  .muted { color:#8aa0c6; }
  .grid { display:grid; grid-template-columns: 1fr 1fr; gap:12px; }
  @media (max-width: 720px) { .grid { grid-template-columns: 1fr; } }
</style>
</head>
<body>
  <div class="card">
    <h1>Strategy Tester Report</h1>
    <div class="muted">Generated by MetaTrader-like Android Tester</div>
  </div>

  <div class="grid">
    <div class="card">
      <h2>Summary</h2>
      <table>
        <tr><th>Net Profit</th><td class="${cls(m.netProfit)}">$net</td></tr>
        <tr><th>Gross Profit</th><td class="pos">$gp</td></tr>
        <tr><th>Gross Loss</th><td class="neg">-$gl</td></tr>
        <tr><th>Total Trades</th><td>${m.totalTrades}</td></tr>
        <tr><th>Win Rate</th><td>$wr</td></tr>
        <tr><th>Profit Factor</th><td>$pf</td></tr>
        <tr><th>Max Drawdown</th><td>$dd</td></tr>
        <tr><th>Expected Payoff</th><td>${fmt(m.expectedPayoff)}</td></tr>
        <tr><th>Recovery Factor</th><td>$rf</td></tr>
        <tr><th>Sharpe-like</th><td>$sharpe</td></tr>
      </table>
    </div>

    <div class="card">
      <h2>Model & Costs</h2>
      <table>
        <tr><th>Modeling</th><td>${cfg.modelingMode.name}</td></tr>
        <tr><th>Initial Balance</th><td>${fmt(cfg.initialBalance)}</td></tr>
        <tr><th>Commission / Lot</th><td>${fmt(cfg.commissionPerLot)}</td></tr>
        <tr><th>Spread</th><td>${cfg.spreadPoints} pts</td></tr>
        <tr><th>Slippage</th><td>${cfg.slippagePoints} pts</td></tr>
        <tr><th>Point Value</th><td>${cfg.pointValue}</td></tr>
        <tr><th>Stop Loss</th><td>$sl</td></tr>
        <tr><th>Take Profit</th><td>$tp</td></tr>
        <tr><th>Risk</th><td>$risk</td></tr>
      </table>
    </div>
  </div>

  <div class="card">
    <h2>Trades</h2>
    <table>
      <tr>
        <th>ID</th><th>Side</th><th>Lots</th><th>Entry Time</th><th>Entry</th>
        <th>Exit Time</th><th>Exit</th><th>Profit</th><th>SL</th><th>TP</th>
      </tr>
      $tradesRows
    </table>
  </div>
</body>
</html>
""".trim()
    }

    private fun buildTradesTable(result: BacktestResult): String {
        val sb = StringBuilder()
        for (t in result.trades) {
            val profit = fmt(t.profit)
            val cls = cls(t.profit)
            val sl = t.stopLoss?.let { String.format(Locale.US, "%.5f", it) } ?: "--"
            val tp = t.takeProfit?.let { String.format(Locale.US, "%.5f", it) } ?: "--"

            sb.append("<tr>")
            sb.append("<td>${t.id}</td>")
            sb.append("<td>${t.side.name}</td>")
            sb.append("<td>${String.format(Locale.US, \"%.2f\", t.lots)}</td>")
            sb.append("<td>${t.entryTimeSec}</td>")
            sb.append("<td>${String.format(Locale.US, \"%.5f\", t.entryPrice)}</td>")
            sb.append("<td>${t.exitTimeSec}</td>")
            sb.append("<td>${String.format(Locale.US, \"%.5f\", t.exitPrice)}</td>")
            sb.append("<td class=\"$cls\">$profit</td>")
            sb.append("<td>$sl</td>")
            sb.append("<td>$tp</td>")
            sb.append("</tr>\n")
        }
        return sb.toString()
    }

    private fun fmt(x: Double): String = String.format(Locale.US, "%+.2f", x)

    private fun cls(x: Double): String = if (x >= 0.0) "pos" else "neg"
}
